### ISSUE TITLE
Two listeners are being registered

### ISSUE THREAD

**Issue by ashleywxwx** [AndrewBell/johnny5#2]
Two message listeners are being registered (and therefore creating double replies). I've opened an issue with the library owner https://github.com/Ullink/simple-slack-api/issues/38

**Comment by redcraft** [comment]
The issue is with connect() method of SlackSession class. The following code will print message three times:

``` java
        SlackSession session = SlackSessionFactory.createWebSocketSlackSession("xoxo-something");
        session.connect();
        session.connect();
        session.connect();
        session.addMessagePostedListener(new SlackMessagePostedListener() {
            public void onEvent(SlackMessagePosted slackMessagePosted, SlackSession slackSession) {
                System.out.println("Message posted: " + slackMessagePosted.getMessageContent());
            }
        });
```

I guess an exception should be thrown if connection is already created.

**Comment by ashleywxwx** [comment]
Thanks for the help @redcraft commit aaaefc4a18ad7d51e4abbe403b9990c07de23070 resolves this
